import Head from 'next/head'
import { NextSeo } from 'next-seo'
import Header from '../components/misc/header'
import Footer from '../components/misc/footer'

export default function CVPage() {
  return (
    <>
      <NextSeo
        title="CV / David Behar Lombrozo"
        description="Software Developer. 10+ years. React, TypeScript, Microfrontends, AWS. Mexico City."
        canonical="https://behar.io/cv"
      />
      <Head>
        <meta name="robots" content="noindex" />
      </Head>
      <div className="cv-brutalist flex flex-col min-h-screen">
        <Header />
        <main style={{ marginTop: '4rem' }}>
          <div className="brutal-topbar"><span>Document: Curriculum Vitae</span><span className="brutal-topbar-date">Rev. 2026-03</span></div>
          <header className="brutal-header"><h1 className="brutal-name">David Behar Lombrozo</h1><div className="brutal-title-row"><span>Software Developer</span><span className="brutal-title-separator">/</span><span>Full Stack Engineer</span><span className="brutal-title-separator">/</span><span>Team Lead</span></div></header>
          <div className="brutal-contact"><span>Mexico City, MX</span><span>+52 55 1698 8310</span><a href="mailto:davbelom@gmail.com">davbelom@gmail.com</a><a href="https://linkedin.com/in/davidbehar" target="_blank" rel="noopener noreferrer">linkedin.com/in/davidbehar</a><a href="https://github.com/behagoras" target="_blank" rel="noopener noreferrer">github.com/behagoras</a></div>
          <div className="brutal-download-bar"><a href="/david-behar-cv.pdf" download="David Behar Lombrozo - CV.pdf" className="brutal-download-btn">[ DOWNLOAD PDF ]</a></div>
          <div className="brutal-section-heading">Summary</div>
          <div className="brutal-summary">AI-native full-stack engineer with 10+ years of experience. Drove Webpack Module Federation migration reducing bundle size by ~70% and page load times by ~35% across 3 React apps serving 500+ users. Specializes in scalable React/TypeScript architecture, CI/CD optimization, and Core Web Vitals. Adopts AI-augmented engineering as a daily practice, using Claude Code and multi-agent orchestration to accelerate design, implementation, refactoring, and testing across the full stack.</div>
          <div className="brutal-section-heading">Technical Skills</div>
          <div className="brutal-skills">
            <div className="brutal-skill-row"><div className="brutal-skill-label">Core Web</div><div className="brutal-skill-value">TypeScript, JavaScript (ES6+), React, Redux, HTML5, CSS3, CSS-in-JS (styled-components), HTTP, State management, DOM</div></div>
            <div className="brutal-skill-row"><div className="brutal-skill-label">AI-Augmented Dev</div><div className="brutal-skill-value">Claude Code, OpenAI Codex, Open Claw Automations, AI-assisted refactoring &amp; testing, Context engineering, Multi-agent orchestration</div></div>
            <div className="brutal-skill-row"><div className="brutal-skill-label">Performance</div><div className="brutal-skill-value">Core Web Vitals optimization, Lighthouse CI, code splitting, API integration, lazy loading, Progressive Web Apps (PWA), bundle optimization, caching strategies</div></div>
            <div className="brutal-skill-row"><div className="brutal-skill-label">Build &amp; Testing</div><div className="brutal-skill-value">Webpack, Jest, Cypress (E2E), Vitest, Storybook, CI/CD, Jenkins, Azure DevOps</div></div>
            <div className="brutal-skill-row"><div className="brutal-skill-label">Backend &amp; Cloud</div><div className="brutal-skill-value">Node.js, API design, REST APIs, GraphQL (AppSync), AWS (Lambda, API Gateway, EventBridge, S3, Serverless Framework)</div></div>
            <div className="brutal-skill-row"><div className="brutal-skill-label">Architecture</div><div className="brutal-skill-value">Microfrontends (Webpack Module Federation), Developer Experience (DX), Responsive Design, Scalable systems, Web Architecture, Event-Driven Patterns</div></div>
            <div className="brutal-skill-row"><div className="brutal-skill-label">Practices</div><div className="brutal-skill-value">Git, Agile/Scrum, OOP, SOLID Principles, TDD, Code reviews, Technical Mentorship</div></div>
          </div>
          <div className="brutal-section-heading">Relevant Experience</div>
          <div className="brutal-experience">
            <div className="brutal-exp-entry"><div className="brutal-exp-header"><div className="brutal-exp-company">Autodesk</div><div className="brutal-exp-meta"><span className="brutal-exp-role">Full Stack Engineer | Team Lead | Platform</span><span className="brutal-exp-location">Mexico City, MX</span><span className="brutal-exp-dates">Nov 2019 - Present</span></div></div><ul className="brutal-exp-bullets"><li>Developed and maintained 3 large-scale React applications comprising 15+ microfrontends and 7 shared libraries (real-time water telemetry, CCTV, asset management, pipe analytics) supporting 500+ users, establishing front-end architecture patterns and reusable platform foundations utilized by 70+ engineers across 3 time zones.</li><li>Directed migration to Webpack Module Federation, decomposing a ~4MB monolithic bundle into 20+ independently deployable modules (~15 MFEs, 3 shell apps, 7 collective libraries) with on-demand route-based loading. Diminished initial bundle size by ~70% and improved page load times by ~35%.</li><li>Built end-to-end serverless upload/download workflows with compliance validation steps using AWS Lambda, API Gateway, and EventBridge, while maintaining 75+ Lambda functions across 15+ microservice backends serving the platform&apos;s microfrontend ecosystem.</li><li>Created 5+ internal packages (auth SDKs, telemetry modules, common UI components) adopted across 5+ teams, shortening developer onboarding from ~2 months to ~2 weeks and reducing AWS authentication setup time by 50% while preserving security standards.</li><li>Led and mentored a team of 4 engineers, ran architecture and code reviews, and instituted CI/CD improvements (incremental builds, pipeline parallelization, independent MFE releases) that reduced build times by 50% and cut deployment pipelines from 12+ to ~5 per shared component change.</li><li>Adopted Claude Code as a daily engineering tool for AI-augmented architecture design, code generation, refactoring, and testing, using multi-agent orchestration across the platform&apos;s microfrontend ecosystem.</li></ul></div>
            <div className="brutal-exp-entry"><div className="brutal-exp-header"><div className="brutal-exp-company">Social Piper</div><div className="brutal-exp-meta"><span className="brutal-exp-role">Senior Front-End Developer</span><span className="brutal-exp-location">Mexico City, MX</span><span className="brutal-exp-dates">Jan 2019 - Nov 2019</span></div></div><ul className="brutal-exp-bullets"><li>Led Vue to React migration and developed a TypeScript component library with Storybook supporting Desktop and Mobile Web; integrated frontend with backend APIs to cut feature delivery time by 25%.</li><li>Improved Core Web Vitals 30-50% through performance audits, code splitting, image optimization, and render optimization strategies.</li><li>Enhanced accessibility of a 30+ collaborative component library (Storybook) with semantic HTML and ARIA attributes, adopted by at least 30+ engineers across 3 apps and 15+ microfrontends.</li></ul></div>
            <div className="brutal-exp-entry"><div className="brutal-exp-header"><div className="brutal-exp-company">Qubit Works</div><div className="brutal-exp-meta"><span className="brutal-exp-role">Head of Operations / Lead Engineer</span><span className="brutal-exp-location">Mexico City, MX</span><span className="brutal-exp-dates">Jan 2015 - Dec 2018</span></div></div><ul className="brutal-exp-bullets"><li>Managed 20+ client projects across web and mobile platforms, architecting React frontends, Node.js backends, and e-commerce solutions while growing the engineering team from 2 to 10+ members and establishing Agile practices, code review culture, and technical training programs.</li><li>Translated 50+ ambiguous client requirements into MVP-first release plans with incremental iterations, delivering projects with cross-functional teams of 3 to 5 (design and engineering) and improving delivery consistency across the agency.</li></ul></div>
            <div className="brutal-exp-entry"><div className="brutal-exp-header"><div className="brutal-exp-company">Farmaldea</div><div className="brutal-exp-meta"><span className="brutal-exp-role">Head of Technology</span><span className="brutal-exp-location">Mexico City, MX</span><span className="brutal-exp-dates">Jan 2014 - Dec 2016</span></div></div><ul className="brutal-exp-bullets"><li>Architected from scratch a digital pharmacy aggregator with point-of-sale capabilities, enabling users to search and purchase medications across 500+ pharmacies through a unified platform.</li><li>Built a REST API integration with GTN&apos;s appointment platform, enabling automated order creation from their scheduling system and periodic inventory synchronization across the pharmacy network.</li></ul></div>
          </div>
          <div className="brutal-two-col">
            <div><div className="brutal-section-heading">Education</div><div className="brutal-education"><div className="brutal-edu-entry"><div className="brutal-edu-year">2014</div><div className="brutal-edu-content"><div className="brutal-edu-school">Universidad Iberoamericana</div><div className="brutal-edu-degree">B.A. | Interactive Design</div><div className="brutal-edu-desc">Speciality in Software Development, Digital Systems, and UX/UI. Foundation in user-centered design and interaction patterns. Mexico City, MX.</div></div></div><div className="brutal-edu-entry"><div className="brutal-edu-year">2021</div><div className="brutal-edu-content"><div className="brutal-edu-school">Platzi Master Bootcamp</div><div className="brutal-edu-degree">Selective Program (Top 1% LATAM)</div><div className="brutal-edu-desc">Completed 100+ advanced courses in computer science, React, Node.js, AWS, algorithms, and distributed systems. Selected as one of the top 1% of the best students of the year 2019.</div></div></div></div></div>
            <div><div className="brutal-section-heading">Languages</div><div className="brutal-languages"><div className="brutal-lang"><div className="brutal-lang-name">Spanish</div><div className="brutal-lang-level">Native</div></div><div className="brutal-lang"><div className="brutal-lang-name">English</div><div className="brutal-lang-level">Advanced</div></div><div className="brutal-lang"><div className="brutal-lang-name">Hebrew</div><div className="brutal-lang-level">Intermediate</div></div></div></div>
          </div>
          <div className="brutal-footer">End of document. No further information.</div>
        </main>
        <Footer />
      </div>
    </>
  )
}
